name: relatoriooffline
description: "Relat√≥rios offline para a defesa civil"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.4.2
  path: ^1.9.1
  http: ^1.2.0
  connectivity_plus: ^6.0.5
  cupertino_icons: ^1.0.8
  geolocator: ^14.0.2
  http_parser: ^4.1.2
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  image_path: lib/assets/logodc.png
  android: true
  ios: true
  remove_alpha_ios: true

flutter:

  uses-material-design: true

  assets:
    - lib/assets/logodc.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700